### ISSUE TITLE
Inline `code` styling issues

### ISSUE THREAD

**Issue by karmaral** [dasmikko/strapi-tiptap-editor#28]
Hello.
First of all, thanks for this wonderful plugin. I've been using tiptap a lot lately and it was painful not to have it inside Strapi.
I've noticed the code styling gets overriden by some CSS reset directives:
```css
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr,
acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong,
sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption,
tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header,
hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
  margin: 0px;
  padding: 0px;
  border: 0px;
  font: inherit; /* here */
  vertical-align: baseline;
}
```

I've managed to fix this by simply specifying the font family explicitly in the stlying.
However a few questions appear:

### Font family
There's a specified `JetBrainsMono` font family in the `pre` directive:
```css
pre {
  background: #0d0d0d;
  color: #fff;
  font-family: "JetBrainsMono", monospace;
  padding: 0.75rem 1rem;
  border-radius: 0.5rem;
}
```
Is that font supposed to be included in the package? I don't have it installed on my machine and it simply defaults to monospace to me.

### Background
Also. the `code` directive states:
```css
code {
  background-color: rgba(#616161, 0.1);
  color: #616161;
}
```
But the built output loses the background color
```css
.iGEXnP .ProseMirror code {
  color: rgb(97, 97, 97);
}
```
This shouldn't happen either, right?

---

If it's okay with you I can make a PR adressing all of this stuff.
